<?php
$lang = Request::current()->param('lang');
$one = Request::current()->param('one');
$two = Request::current()->param('two');
i18n::lang($lang);
?>

<!-- generated by: jsdo.it - http://jsdo.it/phi/cLjT -->
<!-- Copyright phi - http://jsdo.it/phi -->
<!-- Licensed under MIT License - http://www.opensource.org/licenses/mit-license.php -->
<canvas id='world'></canvas>

<script type="text/javascript" src="/public/game/stg2/jsdo.js"></script>

<script type="text/javascript" src="/public/game/stg2/9leap.js"></script>

<script type="text/javascript" src="/public/game/stg2/index2.js"></script>
